version: '2'
services:
  rhd_blinkr_testing:
    build: ../
    volumes:
    - ..:/home/blc
    working_dir: /home/blc
    environment:
    - CONFIG
    - GRID_HOST=blinkr_chrome
    - GRID_PORT=4444

  blinkr_chrome:
    image: selenium/standalone-chrome:3.141.59-krypton
    volumes:
    - /dev/shm:/dev/shm
    ports:
    - "5900"
    links:
    - rhd_blinkr_testing
